// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MshNawy.EntityFrameworkCore;
using Volo.Abp.EntityFrameworkCore;

#nullable disable

namespace MshNawy.EntityFrameworkCore.Migrations
{
    [DbContext(typeof(MshNawyDbContext))]
    [Migration("20260308203948_FeesPoliciesTable")]
    partial class FeesPoliciesTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("_Abp_DatabaseProvider", EfCoreDatabaseProvider.SqlServer)
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("MshNawy.Domain.Fees.FeePolicy", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("EffectiveFrom")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("EffectiveTo")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("EntryFeePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ExitBrokeragePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ExitFeePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("ExitPlatformProfitPercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<decimal>("PaymentFeePercent")
                        .HasColumnType("decimal(5,2)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EffectiveFrom")
                        .HasDatabaseName("IX_FeePolicy_EffectiveFrom");

                    b.ToTable("FeePolicies");
                });

            modelBuilder.Entity("MshNawy.Domain.Wallet.LedgerEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<long>("Amount")
                        .HasColumnType("bigint");

                    b.Property<Guid?>("CompensatingEntryId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreditAccount")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("DebitAccount")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("EntryType")
                        .HasColumnType("int");

                    b.Property<Guid>("IdempotencyKey")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("PostedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("ReferenceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ReferenceEntityType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CreditAccount")
                        .HasDatabaseName("IX_LedgerEntry_CreditAccount");

                    b.HasIndex("DebitAccount")
                        .HasDatabaseName("IX_LedgerEntry_DebitAccount");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("IX_LedgerEntry_IdempotencyKey");

                    b.HasIndex("ReferenceEntityId")
                        .HasDatabaseName("IX_LedgerEntry_ReferenceEntityId");

                    b.ToTable("LedgerEntries");
                });
#pragma warning restore 612, 618
        }
    }
}
